### ISSUE TITLE
데모 앱 만들기

### ISSUE THREAD

**Issue by BlindedShooter** [BlindedShooter/ICP-Prototype#4]
- [x] 채팅 서버 구현
- [x] 앱에서 영상 출력
- [x] 영상 위에 채팅 오버레이

**Comment by BlindedShooter** [comment]
[안드로이드 액티비티 순서도](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=https%3A%2F%2Fwww.draw.io%2F%23G1d1NkGmDB2dFHA8eG6LXZa2jp0gM81_te&layers=1&nav=1#G1d1NkGmDB2dFHA8eG6LXZa2jp0gM81_te)

**Comment by Snowcheck** [comment]
지난번 내가 그렸던 전체 구성도는 작성안되었나? 비 전문가가 보기 쉬울것 같은데.

**Comment by BlindedShooter** [comment]
[안드로이드 액티비티 구현 아웃라인](https://drive.google.com/drive/folders/1vvAIu8MP1Zy_3k9rAXjyHozRCE1seu6-?usp=sharing)

**Comment by BlindedShooter** [comment]
시연용 앱을 개별 프로젝트로 시작한 바람에 이 깃과 통합이 힘들어 https://github.com/OverGrounder/ICP-Demo 로 따로 깃헙 페이지를 만들었습니다. 통합은 추후에 할 예정입니다.
