### ISSUE TITLE
방송화면 전환 이펙트

### ISSUE THREAD

**Issue by OverGrounder** [BlindedShooter/ICP-Prototype#7]
- 방송화면 전환 이펙트
@OverGrounder

**Comment by BlindedShooter** [comment]
#4 와 겹치는것 같은데요

**Comment by OverGrounder** [comment]
구현완료하고 테스트를 해본 결과, 영상과 같이 방송화면 전환이 성공적으로 이루어집니다.
좀더 화면크기와 위치를 옮겨서 조금더 깔끔하게 수정한 뒤 한번 더 테스트영상을 올리겠습니다.

**Comment by OverGrounder** [comment]
아 그러네요
죄송합니다
